- name: populate services facts
  ansible.builtin.service_facts:

- name: set active server variable
  ansible.builtin.set_fact:
    active_server: "{{ inventory_hostname }}"
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s_cluster'] }}"
  when:
    - "'control_plane' in group_names"
    - ansible_facts.services["rke2-server.service"].state == "running"
